# Generated by Django 5.1.7 on 2025-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_nurse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='assigned_ward',
            new_name='assignedWard',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='patients_assigned',
        ),
        migrations.AddField(
            model_name='nurse',
            name='address',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='nurse',
            name='hireDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nurse',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/NurseProfilePic/'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
